const merch = [
  {
    name: "Embers - white t",
    image: "/Assets/Images/embers-wht.jpg",
    price: 200,
    info: "Designed by Daria, made by Black Diamond Clothing, our tshirt features a custom skull inspired by our song 'Embers'",
    id: "embers__tshirt-wht",
    sizes: ["small", "medium", "large", "xl"],
    type: "tshirt",
    isAvailable: true,
  },
  {
    name: "Embers - hoodie",
    image: "/Assets/Images/hoodie.jpg",
    price: 600,
    info: "Designed by Daria, made by Black Diamon Clothing, our hoodie features a custom skull inspired by our song 'Embers'",
    id: "embers-hoodie",
    sizes: ["small", "medium", "large", "xl"],
    type: "hoodie",
    isAvailable: true,
  },
  {
    name: "Embers - black t",
    image: "/Assets/Images/embers-blck.jpg",
    price: 200,
    info: "Designed by Daria, made by Black Diamon Clothing, our tshirt features a custom skull inspired by our song 'Embers'",
    id: "embers__tshirt-blck",
    sizes: ["small", "medium", "large", "xl"],
    type: "tshirt",
    isAvailable: true,
  },
  {
    name: "Dawn - black t",
    image: "/Assets/Images/dawn-tshirt.jpg",
    price: 180,
    info: "Designed by us, made by Diger Distro, our tshirt features our own take on the 'Delta' symbol used on our EP 'Dawn'",
    id: "dawn__tshirt-blck",
    sizes: ["small", "medium", "large", "xl"],
    type: "tshirt",
    isAvailable: true,
  },
  {
    name: "Patch",
    image: "/Assets/Images/patch.jpg",
    price: 40,
    info: "Our own logo sewed onto a black patch with high quality stitching",
    id: "patch",
    sizes: false,
    type: "misc",
    isAvailable: true,
  },
  {
    name: "Dawn - cd",
    image: "/Assets/Images/Dawn-CD.jpeg",
    price: 180,
    info: "A cd with our debut EP Dawn",
    id: "dawn-cd",
    sizes: false,
    type: "misc",
    isAvailable: true,
  },
];

export default merch;
