const merch = [
  {
    name: "Embers - white t",
    image: "./assets/images/embers-wht.jpg",
    price: 250,
    info: "Designed by Daria, made by Black Diamond Clothing, our tshirt features a custom skull inspired by our song 'Embers'",
    id: "embers__tshirt-wht",
    sizes: ["small", "medium", "large", "xl"],
    type: "tshirt",
    isAvailable: true,
  },
  {
    name: "Embers - hoodie",
    image: "./assets/images/hoodie.jpg",
    price: 600,
    info: "Designed by Daria, made by Black Diamon Clothing, our hoodie features a custom skull inspired by our song 'Embers'",
    id: "embers-hoodie",
    sizes: ["small", "medium", "large", "xl"],
    type: "hoodie",
    isAvailable: true,
  },
  {
    name: "Embers - black t",
    image: "./assets/images/embers-blck.jpg",
    price: 250,
    info: "Designed by Daria, made by Black Diamon Clothing, our tshirt features a custom skull inspired by our song 'Embers'",
    id: "embers__tshirt-blck",
    sizes: ["small", "medium", "large", "xl"],
    type: "tshirt",
    isAvailable: true,
  },
  {
    name: "Dawn - black t",
    image: "./assets/images/dawn-tshirt.jpg",
    price: 200,
    info: "Designed by us, made by Diger Distro, our tshirt features our own take on the 'Delta' symbol used on our EP 'Dawn'",
    id: "dawn__tshirt-blck",
    sizes: ["small", "medium", "large", "xl"],
    type: "tshirt",
    isAvailable: true,
  },
  {
    name: "Patch",
    image: "./assets/images/patch.jpg",
    price: 50,
    info: "Our own logo sewed onto a black patch with high quality stitching",
    id: "patch",
    sizes: [],
    type: "misc",
    isAvailable: true,
  },
  {
    name: "AMP - cd",
    image: "./assets/images/AMP-cd.png",
    price: 200,
    info: "A collectors CD with all bands signed on Braak Records",
    id: "amp-cd",
    sizes: [],
    type: "misc",
    isAvailable: true,
    url: "https://braakrecords.com/",
  },
];
